sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=ae-waiting-time-dashboards
    - ORG=g0vhk

services:
  - docker

script:
    - echo "MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN" > .env
    - yarn install
    - yarn build

after_success:
    - docker build -t $ORG/$REPO:$COMMIT .
    - export TAG='latest'
    - docker tag $ORG/$REPO:$COMMIT $ORG/$REPO:$TAG
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $ORG/$REPO